version: "3"
services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: "postgres"
    restart: always
    ports:
      - 5432:5432
    volumes:
      - psql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tilios
      - POSTGRES_PASSWORD=thefirst
      - POSTGRES_DB=puro_dev

  api-service:
    restart: always
    image: services_api-service
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: "api-service"
    volumes:
    - ./api:/opt/app
    ports:
      - 1111:80

  web-frontend-service:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web/build:/srv/www/static
      - ./web/nginx/default.conf:/etc/nginx/conf.d/default.conf
volumes:
  psql_data:
    driver: local
